name: Publish Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push MTGO Base
        uses: docker/build-push-action@v5
        with:
          context: ./mtgo
          push: true
          tags: |
            videreproject/mtgo:latest
            videreproject/mtgo:headless
            videreproject/mtgo:x11
            videreproject/mtgo:wayland

      - name: Build and push MTGOSDK
        uses: docker/build-push-action@v5
        with:
          context: ./mtgosdk
          build-args: |
             BASE_IMAGE=videreproject/mtgo:headless
          push: true
          tags: |
            videreproject/mtgosdk:latest
            videreproject/mtgosdk:headless
            videreproject/mtgosdk:x11
            videreproject/mtgosdk:wayland
